### ISSUE TITLE
Request about DHTnew

### ISSUE THREAD

**Issue by NiamorV** [RobTillaart/DHTNew#1]
Hello Rob,

I'm using your DHT library DHT new, and it's working really well;

But I'm trying to declare a table of DHTnew sondes (because I have a lot of sondes, and it will really simplify my code).

Could you tell me, if it will be possible for you to make an evolution in this library in order to be able to declare a table of sondes?
Something like DHTNEW MyProbe[8];
Then to declare the pins with a function call?

**Comment by RobTillaart** [comment]
Added an example to use an array of DHT sensors.
