### ISSUE TITLE
setTempOffset and setHumOffset

### ISSUE THREAD

**Issue by us292231** [RobTillaart/DHTNew#74]
It looks like the header has definitions for setTempOffset/getTempOffset and setHumOffset/getHumOffset and the class has the variables, but it doesn't seem that the implementation is missing.

**Comment by us292231** [comment]
Ok, I'm an idiot.  I see it now...

**Comment by RobTillaart** [comment]
Q: do I need to improve documentation, comments or readme.md ?

**Comment by us292231** [comment]
Hi,

Your code and documentation are really nice, no improvements needed.  Also, a big thank you for putting it out there, it has really helped me.  Your efforts are very much appreciated.

I made a really bad mistake and jumped to a conclusion that was wrong.  I forgot to connect the dots in my code and didn't catch that until just after I clicked save...  Totally my bad in multiple ways.

Thanks for asking,
Jim
________________________________
