### ISSUE TITLE
DHT22 registers as type 70 in 0.4.14

### ISSUE THREAD

**Issue by simonbogh** [RobTillaart/DHTNew#81]
DHT22 registers as type 70 in `0.4.14`. Works as intended in `0.4.13` where it registers as type 22.

**Comment by RobTillaart** [comment]
Thanks for this issue, I will look into it asap.

What processor do you use?
does the DHT22 give correct readings?

**Comment by simonbogh** [comment]
Thanks. 

I use an esp-wroom-32, the board is a Wemos Lolin32 ESP32 OLED.

**Comment by RobTillaart** [comment]
OK, so the problem is the automatic recognition of the type.

**Comment by simonbogh** [comment]
Looks like it. If I use `mySensor.setType(22);` in `0.4.14` it gives correct readings and type.

**Comment by RobTillaart** [comment]
DHTNEW.cpp
```cpp
int DHTNEW::read()
{
  ...
  //  AUTODETECT

  _type = 22;
  _wakeupDelay = DHTLIB_DHT_WAKEUP;
  int rv = _read();
  if (rv == DHTLIB_OK) return rv;

  _type = 11;
  _wakeupDelay = DHTLIB_DHT11_WAKEUP;
  rv = _read();
  if (rv == DHTLIB_OK) return rv;

  //  experimental 0.4.14
  _type = 70;
  _wakeupDelay = DHTLIB_SI7021_WAKEUP;
  rv = _read();
  if (rv == DHTLIB_OK) return rv;

  _type = 0; // retry next time
  return rv;
}
```

The code tries the DHT22 before the Si7021, so the detection order is OK too.

**Comment by RobTillaart** [comment]
@simonbogh 

Can you in your code before the very first call to DHT.read() add a delay of 2 seconds?

Assumption is that the sensor needs time to wake up and that it just has not had enough time for it.
Thus failing type == 22 , tries type == 11 - which fails too and finally succeeds in being a type 70.

**Comment by RobTillaart** [comment]
Tried adding a delay(1000) in the auto detect an the SNR error disappeared in **endless.ino**.

So I assume this (first) error already existed in the 0.4.13 and before. Lets test.

**Comment by simonbogh** [comment]
That does the trick. Even a small delay of 500 ms works on my end 👍

**Comment by RobTillaart** [comment]
Created a develop branch, added a delay of max 1 second in first call

~line 123 dhtnew.cpp

added 
```cpp
  //  AUTODETECT
  //  make sure sensor had time to wake up.
  while (millis() < 1000);
```

**Comment by RobTillaart** [comment]
Going to merge the fix.

**Comment by RobTillaart** [comment]
@simonbogh 
Thanks!
