### ISSUE TITLE
Shows wrong type 

### ISSUE THREAD

**Issue by MickyRoth** [RobTillaart/DHTNew#94]
I have a DHT11 (the blue sensor), but it shows type "22" in the dhtnew_test sketch.
Temp and Humid readings are OK, though. Is this a known problem?

**Comment by RobTillaart** [comment]
Thanks for the issue,
Not a known problem, the library has been around for a long time and Ido not recall a similar issue.

The DHT11 does only integers, where the DHT22 has one decimal.
Do you override the type to get the output?

**Comment by RobTillaart** [comment]
Assuming there are no further questions I close this issue. Feel free to reopen if needed.
