### ISSUE TITLE
Small documentation improvement: add unity

### ISSUE THREAD

**Issue by koocotte** [RobTillaart/DHTNew#95]
Hello,

A small suggestion to improve documentation: explicit unity :

Document getHumidity() return a value between 0.0-1.0 or between 0.0-100.0, to be interpreted as a percent of humidity.

float getTemperature() returns temperature as °C or °F ?

Thanks

**Comment by RobTillaart** [comment]
Thanks for this issue,
Will have a look a the documentation to see how to improve.

**Comment by RobTillaart** [comment]
Created a develop branch and a PR to improve the documentation.
Also includes some other pending updates.
